title: JRuyi
url: http://www.jruyi.org
author:
  name: "Agemo Cui"
  email: "agemocui@jruyi.org"
markdown: redcarpet
permalink: pretty
paginate_path: 'news/page:num'
pygments: true
paginate: 10 
jruyi-api-version: 1.2.0
jruyi-version: 1.2.1

